"""
Report generator module - generates AI-powered comprehensive reports
"""
import datetime
from decimal import Decimal
from typing import Dict, Any, List
from pathlib import Path
import config
from blob_uploader import BlobUploader

class DecimalEncoder:
    """Not needed anymore - no JSON generation"""
    pass

class ReportGenerator:
    def __init__(self):
        self.output_dir = Path(config.REPORT_OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.blob_uploader = BlobUploader()
    
    def generate_department_report(self, department_id: str, department_name: str, report_data: Dict[str, Any], ai_report: str = None) -> str:
        """Generate AI-powered comprehensive department progress report (Markdown only)"""
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Generate only markdown report with AI content
        md_report_path = self._generate_markdown_report(report_data, department_id, timestamp, ai_report)
        
        print(f"✓ AI Report generated: {md_report_path}")
        
        # Upload to Azure Blob Storage and save URL to database
        blob_url = self.blob_uploader.upload_report(md_report_path, department_id, department_name)
        if blob_url:
            print(f"✓ Report uploaded to blob: {blob_url}")
        
        return str(md_report_path)
    
    def _generate_markdown_report(self, report_data: Dict[str, Any], department_id: str, timestamp: str, ai_report: str = None) -> str:
        """Generate a comprehensive markdown report with AI-generated content"""
        md_filename = f"department_{report_data.get('department_name', 'Unknown').replace(' ', '_')}_{timestamp}.md"
        md_path = self.output_dir / md_filename
        
        department_name = report_data.get('department_name', 'Unknown Department')
        generated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Start with header
        md_content = f"""# {department_name} - Progress Tracking Report

**Generated:** {generated_at}  
**Department ID:** {department_id}  
**Report Type:** Comprehensive Progress Analysis

---

"""
        
        # Add AI-generated comprehensive report (main content)
        if ai_report:
            md_content += ai_report
            md_content += "\n\n---\n\n"
        else:
            md_content += "## AI Report Generation Failed\n\nPlease check the logs for errors.\n\n---\n\n"
        
        # Add raw data summary at the end for reference
        summary_counts = report_data.get('summary_counts', {})
        md_content += f"""## Data Summary (Reference)

### Overall Statistics
- **Total Grievances:** {summary_counts.get('total_grievances', 0)}
- **Total Officers:** {summary_counts.get('total_officers', 0)}
- **Total Projects:** {summary_counts.get('total_projects', 0)}
- **Total Tenders:** {summary_counts.get('total_tenders', 0)}
- **Total Equipment:** {summary_counts.get('total_equipment', 0)}
- **Total Materials:** {summary_counts.get('total_materials', 0)}
- **Budget Allocations:** {summary_counts.get('total_budget_allocations', 0)}
- **Active Alerts:** {summary_counts.get('active_alerts', 0)}

"""
        
        # Add performance metrics
        performance = report_data.get('performance_metrics', {})
        if performance:
            md_content += f"""### Performance Metrics
- **Resolution Rate:** {performance.get('resolution_rate', 0)}%
- **Average Resolution Time:** {performance.get('average_resolution_time_days', 0)} days
- **Average Rating:** {performance.get('average_rating', 0)}/5
- **Performance Score:** {performance.get('performance_score', 0)}/100

"""
        
        # Add resource utilization summary
        resources = report_data.get('resource_utilization', {})
        if resources:
            officers = resources.get('officers', {})
            budget = resources.get('budget', {})
            equipment = resources.get('equipment', {})
            
            md_content += f"""### Resource Utilization
- **Officer Utilization:** {officers.get('officer_utilization', 0):.1f}%
- **Budget Utilization:** {budget.get('utilization_percent', 0):.1f}%
- **Equipment Availability:** {equipment.get('availability_percent', 0):.1f}%

"""
        
        md_content += "\n---\n\n*This report was generated by the Progress Tracking Agent powered by DeepSeek AI*\n"
        
        # Save markdown file
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return str(md_path)
    
    def generate_consolidated_report(self, all_departments_data: List[Dict[str, Any]]) -> str:
        """Generate a consolidated report for all departments"""
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"consolidated_report_{timestamp}.md"
        report_path = self.output_dir / report_filename
        
        # Aggregate data
        total_grievances = sum(d.get("grievance_analysis", {}).get("total_grievances", 0) for d in all_departments_data)
        total_resolved = sum(d.get("performance_metrics", {}).get("resolved_count", 0) for d in all_departments_data)
        
        md_content = f"""# Consolidated Progress Report - All Departments

**Generated:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Total Departments:** {len(all_departments_data)}

---

## Overall Summary

- **Total Grievances Across All Departments:** {total_grievances}
- **Total Resolved:** {total_resolved}
- **Overall Resolution Rate:** {(total_resolved / total_grievances * 100) if total_grievances > 0 else 0:.2f}%

---

## Department Performance Overview

"""
        
        # Sort departments by performance score
        sorted_depts = sorted(
            all_departments_data,
            key=lambda d: d.get("performance_metrics", {}).get("performance_score", 0),
            reverse=True
        )
        
        for dept in sorted_depts:
            dept_name = dept.get("department_name", "Unknown")
            perf = dept.get("performance_metrics", {})
            griev = dept.get("grievance_analysis", {})
            
            md_content += f"""### {dept_name}

- **Performance Score:** {perf.get('performance_score', 0)}/100
- **Total Grievances:** {griev.get('total_grievances', 0)}
- **Resolution Rate:** {perf.get('resolution_rate', 0)}%
- **Average Rating:** {perf.get('average_rating', 0)}/5
- **Overdue:** {griev.get('overdue_count', 0)}
- **Stalled:** {griev.get('stalled_count', 0)}

"""
        
        md_content += "\n---\n\n*Consolidated report generated by Progress Tracking Agent*\n"
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        print(f"✓ Consolidated report generated: {report_path}")
        return str(report_path)
