-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.aiinsights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  grievance_id uuid,
  insight_type character varying NOT NULL,
  priority character varying DEFAULT 'medium'::character varying,
  confidence_score numeric,
  title character varying NOT NULL,
  description text NOT NULL,
  ai_explanation jsonb,
  recommended_action text,
  metrics jsonb,
  is_accepted boolean,
  accepted_by_officer_id uuid,
  accepted_at timestamp with time zone,
  is_dismissed boolean DEFAULT false,
  dismissed_reason text,
  embedding USER-DEFINED,
  CONSTRAINT aiinsights_pkey PRIMARY KEY (id),
  CONSTRAINT aiinsights_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT aiinsights_accepted_by_officer_id_fkey FOREIGN KEY (accepted_by_officer_id) REFERENCES public.users(id)
);
CREATE TABLE public.auditlog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  timestamp timestamp with time zone DEFAULT now(),
  actor_id uuid,
  actor_name character varying,
  actor_role character varying,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  details jsonb,
  ip_address character varying,
  user_agent text,
  embedding USER-DEFINED,
  CONSTRAINT auditlog_pkey PRIMARY KEY (id),
  CONSTRAINT auditlog_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.budget_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  department_id uuid NOT NULL,
  allocation_id uuid,
  grievance_id uuid,
  alert_type character varying NOT NULL,
  severity character varying CHECK (severity::text = ANY (ARRAY['Low'::character varying, 'Medium'::character varying, 'High'::character varying, 'Critical'::character varying]::text[])),
  title character varying NOT NULL,
  description text,
  alert_data jsonb DEFAULT '{}'::jsonb,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  resolution_notes text,
  notified_officers jsonb DEFAULT '[]'::jsonb,
  is_acknowledged boolean DEFAULT false,
  CONSTRAINT budget_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT budget_alerts_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT budget_alerts_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT budget_alerts_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT budget_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.budget_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  allocation_id character varying NOT NULL UNIQUE,
  department_id uuid NOT NULL,
  allocation_amount numeric NOT NULL,
  allocation_date date NOT NULL,
  financial_year character varying NOT NULL,
  scheme_name character varying,
  allocation_purpose text,
  allocated_by character varying,
  approval_authority character varying,
  budget_type character varying CHECK (budget_type::text = ANY (ARRAY['Operational'::character varying, 'Emergency'::character varying, 'Maintenance'::character varying, 'Infrastructure'::character varying]::text[])),
  budget_source character varying CHECK (budget_source::text = ANY (ARRAY['State Government'::character varying, 'Central Government'::character varying, 'Municipal Corporation'::character varying, 'Special Grant'::character varying]::text[])),
  status character varying DEFAULT 'Active'::character varying CHECK (status::text = ANY (ARRAY['Active'::character varying, 'Exhausted'::character varying, 'Cancelled'::character varying, 'On Hold'::character varying]::text[])),
  documents jsonb DEFAULT '[]'::jsonb,
  remarks text,
  is_active boolean DEFAULT true,
  CONSTRAINT budget_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT budget_allocations_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.budget_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  allocation_id uuid,
  grievance_id uuid,
  document_type character varying NOT NULL,
  document_name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  file_size bigint,
  uploaded_by uuid,
  uploaded_by_name character varying,
  upload_date timestamp with time zone DEFAULT now(),
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  verification_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT budget_documents_pkey PRIMARY KEY (id),
  CONSTRAINT budget_documents_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT budget_documents_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT budget_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT budget_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.budget_usage_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  department_id uuid NOT NULL,
  financial_year character varying NOT NULL,
  month character varying,
  total_allocated numeric DEFAULT 0,
  total_used numeric DEFAULT 0,
  total_remaining numeric DEFAULT 0,
  utilization_percentage numeric DEFAULT 0,
  category_breakdown jsonb DEFAULT '{}'::jsonb,
  grievances_funded integer DEFAULT 0,
  grievances_resolved integer DEFAULT 0,
  avg_cost_per_grievance numeric DEFAULT 0,
  labor_total numeric DEFAULT 0,
  material_total numeric DEFAULT 0,
  equipment_total numeric DEFAULT 0,
  transport_total numeric DEFAULT 0,
  contractor_total numeric DEFAULT 0,
  budget_efficiency_score numeric DEFAULT 0,
  cost_efficiency_score numeric DEFAULT 0,
  analytics_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT budget_usage_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT budget_usage_analytics_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  district_id uuid NOT NULL,
  taluka_id uuid,
  city_code character varying NOT NULL UNIQUE,
  city_name character varying NOT NULL,
  city_type character varying CHECK (city_type::text = ANY (ARRAY['Municipal Corporation'::character varying, 'Municipality'::character varying, 'Nagar Panchayat'::character varying, 'Town'::character varying]::text[])),
  population bigint,
  area_sq_km numeric,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT cities_pkey PRIMARY KEY (id),
  CONSTRAINT cities_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT cities_taluka_id_fkey FOREIGN KEY (taluka_id) REFERENCES public.talukas(id)
);
CREATE TABLE public.citizens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  telegram_id bigint UNIQUE,
  phone character varying NOT NULL,
  username character varying,
  full_name character varying,
  latitude numeric,
  longitude numeric,
  location_address text,
  is_registered boolean DEFAULT false,
  is_active boolean DEFAULT true,
  user_id uuid,
  email character varying UNIQUE,
  password_hash character varying,
  address text,
  email_verified boolean DEFAULT false,
  verification_token text,
  reset_token text,
  reset_token_expiry timestamp with time zone,
  last_login timestamp with time zone,
  profile_image text,
  total_grievances integer DEFAULT 0,
  resolved_grievances integer DEFAULT 0,
  embedding USER-DEFINED,
  date_of_birth date,
  gender character varying,
  aadhaar_number character varying,
  occupation character varying,
  verification_token_expiry timestamp with time zone,
  CONSTRAINT citizens_pkey PRIMARY KEY (id),
  CONSTRAINT citizens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.city_officials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  city character varying NOT NULL,
  district character varying NOT NULL,
  designation character varying NOT NULL,
  corporation_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT city_officials_pkey PRIMARY KEY (id),
  CONSTRAINT city_officials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contractors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contractor_id character varying NOT NULL UNIQUE,
  company_name character varying NOT NULL,
  contact_person character varying,
  phone character varying,
  email character varying,
  address text,
  specialization text,
  performance_score numeric,
  active_projects integer DEFAULT 0,
  completed_projects integer DEFAULT 0,
  avg_completion_time numeric,
  contract_value numeric,
  is_active boolean DEFAULT true,
  documents jsonb,
  certifications jsonb,
  embedding USER-DEFINED,
  CONSTRAINT contractors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.department_dashboards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_data jsonb NOT NULL DEFAULT '{"alerts": [], "aiInsights": [], "activityFeed": [], "resourceHealth": {"staff": {"status": "Unknown", "required": 0, "available": 0, "utilizationRate": 0}, "budget": {"spent": 0, "status": "Unknown", "allocated": 0, "remaining": 0, "utilizationPercent": 0}, "equipment": {"total": 0, "status": "Unknown", "available": 0, "availabilityPercent": 0}, "materials": {"status": "Unknown", "adequate": 0, "critical": 0, "lowStock": 0}}, "zonePerformance": [], "grievanceOverview": {"monthlyTrend": "+0%", "totalGrievances": 0, "overdueGrievances": 0, "pendingGrievances": 0, "resolvedGrievances": 0, "emergencyGrievances": 0}, "performanceMetrics": {"kpiScore": 0, "kpiTarget": 90, "slaCompliance": 0, "performanceTrend": "+0%", "avgResolutionTime": "0 days", "citizenSatisfaction": 0}, "tenderProjectStatus": {"activeTenders": 0, "activeProjects": 0, "projectsAtRisk": 0, "projectsDelayed": 0}, "departmentHealthScore": {"trend": "Stable", "status": "Unknown", "maxScore": 100, "lastUpdated": null, "overallScore": 0}}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_calculated_at timestamp with time zone,
  embedding USER-DEFINED,
  department_id uuid UNIQUE,
  CONSTRAINT department_dashboards_pkey PRIMARY KEY (id),
  CONSTRAINT department_dashboards_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.department_hierarchy (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  department_id uuid NOT NULL,
  state_id uuid,
  district_id uuid,
  city_id uuid,
  ward_id uuid,
  head_official_id uuid,
  office_address text,
  office_phone character varying,
  office_email character varying,
  staff_count integer DEFAULT 0,
  annual_budget numeric,
  budget_utilized numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT department_hierarchy_pkey PRIMARY KEY (id),
  CONSTRAINT department_hierarchy_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT department_hierarchy_ward_id_fkey FOREIGN KEY (ward_id) REFERENCES public.wards(id),
  CONSTRAINT department_hierarchy_head_official_id_fkey FOREIGN KEY (head_official_id) REFERENCES public.government_officials(id),
  CONSTRAINT department_hierarchy_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT department_hierarchy_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id),
  CONSTRAINT department_hierarchy_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.departmentknowledgebase (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  department_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  file_name character varying,
  file_url text,
  file_type character varying,
  file_size bigint,
  uploaded_by_officer_id uuid,
  category character varying,
  tags jsonb,
  content_text text,
  embedding USER-DEFINED,
  view_count integer DEFAULT 0,
  download_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT departmentknowledgebase_pkey PRIMARY KEY (id),
  CONSTRAINT departmentknowledgebase_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT departmentknowledgebase_uploaded_by_officer_id_fkey FOREIGN KEY (uploaded_by_officer_id) REFERENCES public.users(id)
);
CREATE TABLE public.departmentofficers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL UNIQUE,
  department_id uuid NOT NULL,
  staff_id character varying UNIQUE,
  role character varying NOT NULL,
  zone character varying,
  ward character varying,
  status character varying DEFAULT 'available'::character varying,
  workload integer DEFAULT 0,
  specialization text,
  performance_score numeric,
  avg_resolution_time numeric,
  total_assigned integer DEFAULT 0,
  total_resolved integer DEFAULT 0,
  current_tasks jsonb DEFAULT '[]'::jsonb,
  skills jsonb,
  certifications jsonb,
  embedding USER-DEFINED,
  CONSTRAINT departmentofficers_pkey PRIMARY KEY (id),
  CONSTRAINT departmentofficers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT departmentofficers_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name character varying NOT NULL UNIQUE,
  description text,
  contact_email character varying,
  contact_phone character varying,
  is_active boolean DEFAULT true,
  head_officer_id uuid,
  budget_allocated numeric,
  budget_used numeric DEFAULT 0,
  total_grievances integer DEFAULT 0,
  resolved_grievances integer DEFAULT 0,
  avg_resolution_time numeric,
  performance_score numeric,
  embedding USER-DEFINED,
  address text,
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_head_officer_id_fkey FOREIGN KEY (head_officer_id) REFERENCES public.departmentofficers(id)
);
CREATE TABLE public.district_officials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  district character varying NOT NULL,
  designation character varying NOT NULL,
  jurisdiction text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT district_officials_pkey PRIMARY KEY (id),
  CONSTRAINT district_officials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.districts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  state_id uuid NOT NULL,
  district_code character varying NOT NULL UNIQUE,
  district_name character varying NOT NULL,
  headquarters character varying,
  population bigint,
  area_sq_km numeric,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT districts_pkey PRIMARY KEY (id),
  CONSTRAINT districts_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id)
);
CREATE TABLE public.embedding_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  table_name text NOT NULL,
  row_id text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  last_attempt_at timestamp with time zone,
  error text,
  CONSTRAINT embedding_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  equipment_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  type character varying NOT NULL,
  department_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'available'::equipment_status,
  location character varying,
  assigned_to_officer_id uuid,
  condition character varying DEFAULT 'good'::character varying,
  utilization_rate numeric DEFAULT 0,
  next_maintenance timestamp with time zone,
  last_maintenance timestamp with time zone,
  specifications jsonb,
  maintenance_history jsonb DEFAULT '[]'::jsonb,
  embedding USER-DEFINED,
  CONSTRAINT equipment_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT equipment_assigned_to_officer_id_fkey FOREIGN KEY (assigned_to_officer_id) REFERENCES public.users(id)
);
CREATE TABLE public.escalation_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  rule_name character varying NOT NULL,
  rule_description text,
  trigger_type character varying CHECK (trigger_type::text = ANY (ARRAY['SLA Breach'::character varying, 'No Response'::character varying, 'Priority'::character varying, 'Category'::character varying, 'Manual'::character varying]::text[])),
  trigger_conditions jsonb DEFAULT '{}'::jsonb,
  from_role_level character varying CHECK (from_role_level::text = ANY (ARRAY['Ward'::character varying, 'City'::character varying, 'Taluka'::character varying, 'District'::character varying, 'State'::character varying]::text[])),
  to_role_level character varying CHECK (to_role_level::text = ANY (ARRAY['Ward'::character varying, 'City'::character varying, 'Taluka'::character varying, 'District'::character varying, 'State'::character varying, 'Central'::character varying]::text[])),
  is_automatic boolean DEFAULT false,
  requires_approval boolean DEFAULT false,
  notify_officials boolean DEFAULT true,
  notification_template text,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 1,
  CONSTRAINT escalation_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.expense_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cost_tracking_id uuid NOT NULL,
  grievance_id uuid NOT NULL,
  created_by uuid,
  created_at_step timestamp with time zone DEFAULT now(),
  verified_by uuid,
  verified_at timestamp with time zone,
  verification_notes text,
  approved_by_finance uuid,
  approved_by_finance_at timestamp with time zone,
  finance_notes text,
  approved_by_head uuid,
  approved_by_head_at timestamp with time zone,
  head_notes text,
  paid_at timestamp with time zone,
  payment_reference character varying,
  current_status character varying DEFAULT 'Created'::character varying CHECK (current_status::text = ANY (ARRAY['Created'::character varying, 'Verified'::character varying, 'Approved'::character varying, 'Paid'::character varying, 'Rejected'::character varying]::text[])),
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  CONSTRAINT expense_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT expense_approvals_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT expense_approvals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT expense_approvals_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT expense_approvals_approved_by_finance_fkey FOREIGN KEY (approved_by_finance) REFERENCES public.users(id),
  CONSTRAINT expense_approvals_approved_by_head_fkey FOREIGN KEY (approved_by_head) REFERENCES public.users(id),
  CONSTRAINT expense_approvals_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id)
);
CREATE TABLE public.faqs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  question text NOT NULL,
  answer text NOT NULL,
  category character varying,
  department_id uuid,
  embedding USER-DEFINED,
  view_count integer DEFAULT 0,
  helpful_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT faqs_pkey PRIMARY KEY (id),
  CONSTRAINT faqs_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.government_officials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  state_id uuid,
  district_id uuid,
  taluka_id uuid,
  city_id uuid,
  ward_id uuid,
  gram_panchayat_id uuid,
  department_id uuid,
  reports_to uuid,
  employee_code character varying NOT NULL UNIQUE,
  designation character varying NOT NULL,
  office_address text,
  office_phone character varying,
  office_email character varying,
  appointment_date date,
  joining_date date,
  status character varying DEFAULT 'Active'::character varying CHECK (status::text = ANY (ARRAY['Active'::character varying, 'On Leave'::character varying, 'Transferred'::character varying, 'Retired'::character varying, 'Suspended'::character varying]::text[])),
  access_level integer DEFAULT 1,
  can_approve_grievances boolean DEFAULT false,
  can_allocate_budget boolean DEFAULT false,
  can_assign_tasks boolean DEFAULT false,
  can_manage_officers boolean DEFAULT false,
  qualifications text,
  specialization character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  CONSTRAINT government_officials_pkey PRIMARY KEY (id),
  CONSTRAINT government_officials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT government_officials_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.government_roles(id),
  CONSTRAINT government_officials_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id),
  CONSTRAINT government_officials_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT government_officials_taluka_id_fkey FOREIGN KEY (taluka_id) REFERENCES public.talukas(id),
  CONSTRAINT government_officials_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT government_officials_ward_id_fkey FOREIGN KEY (ward_id) REFERENCES public.wards(id),
  CONSTRAINT government_officials_gram_panchayat_id_fkey FOREIGN KEY (gram_panchayat_id) REFERENCES public.gram_panchayats(id),
  CONSTRAINT government_officials_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT government_officials_reports_to_fkey FOREIGN KEY (reports_to) REFERENCES public.government_officials(id)
);
CREATE TABLE public.government_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role_code character varying NOT NULL UNIQUE,
  role_name character varying NOT NULL,
  role_level character varying NOT NULL CHECK (role_level::text = ANY (ARRAY['Central'::character varying, 'State'::character varying, 'District'::character varying, 'Taluka'::character varying, 'City'::character varying, 'Ward'::character varying, 'Gram Panchayat'::character varying]::text[])),
  role_type character varying NOT NULL CHECK (role_type::text = ANY (ARRAY['Administrative'::character varying, 'Department'::character varying, 'Technical'::character varying, 'Support'::character varying]::text[])),
  description text,
  permissions jsonb DEFAULT '[]'::jsonb,
  hierarchy_rank integer,
  is_active boolean DEFAULT true,
  CONSTRAINT government_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gram_panchayats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  taluka_id uuid NOT NULL,
  gp_code character varying NOT NULL UNIQUE,
  gp_name character varying NOT NULL,
  population bigint,
  area_sq_km numeric,
  villages_count integer,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT gram_panchayats_pkey PRIMARY KEY (id),
  CONSTRAINT gram_panchayats_taluka_id_fkey FOREIGN KEY (taluka_id) REFERENCES public.talukas(id)
);
CREATE TABLE public.grievance_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL,
  assigned_to_official_id uuid NOT NULL,
  assigned_by_official_id uuid,
  department_id uuid,
  assignment_type character varying CHECK (assignment_type::text = ANY (ARRAY['Primary'::character varying, 'Secondary'::character varying, 'Escalated'::character varying, 'Transferred'::character varying, 'Collaborative'::character varying]::text[])),
  status character varying DEFAULT 'Assigned'::character varying CHECK (status::text = ANY (ARRAY['Assigned'::character varying, 'Accepted'::character varying, 'In Progress'::character varying, 'Completed'::character varying, 'Rejected'::character varying, 'Transferred'::character varying]::text[])),
  assigned_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  completed_at timestamp with time zone,
  due_date timestamp with time zone,
  priority character varying CHECK (priority::text = ANY (ARRAY['Low'::character varying, 'Medium'::character varying, 'High'::character varying, 'Critical'::character varying]::text[])),
  assignment_notes text,
  completion_notes text,
  sla_hours integer,
  is_sla_breached boolean DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT grievance_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT grievance_assignments_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT grievance_assignments_assigned_to_official_id_fkey FOREIGN KEY (assigned_to_official_id) REFERENCES public.government_officials(id),
  CONSTRAINT grievance_assignments_assigned_by_official_id_fkey FOREIGN KEY (assigned_by_official_id) REFERENCES public.government_officials(id),
  CONSTRAINT grievance_assignments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.grievance_location_mapping (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL UNIQUE,
  state_id uuid,
  district_id uuid,
  taluka_id uuid,
  city_id uuid,
  ward_id uuid,
  gram_panchayat_id uuid,
  latitude numeric,
  longitude numeric,
  address text,
  location_source character varying CHECK (location_source::text = ANY (ARRAY['GPS'::character varying, 'Address'::character varying, 'Manual'::character varying, 'IP'::character varying]::text[])),
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  CONSTRAINT grievance_location_mapping_pkey PRIMARY KEY (id),
  CONSTRAINT grievance_location_mapping_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT grievance_location_mapping_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id),
  CONSTRAINT grievance_location_mapping_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT grievance_location_mapping_taluka_id_fkey FOREIGN KEY (taluka_id) REFERENCES public.talukas(id),
  CONSTRAINT grievance_location_mapping_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT grievance_location_mapping_ward_id_fkey FOREIGN KEY (ward_id) REFERENCES public.wards(id),
  CONSTRAINT grievance_location_mapping_gram_panchayat_id_fkey FOREIGN KEY (gram_panchayat_id) REFERENCES public.gram_panchayats(id),
  CONSTRAINT grievance_location_mapping_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.government_officials(id)
);
CREATE TABLE public.grievancecomments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment text NOT NULL,
  is_internal boolean DEFAULT false,
  attachments jsonb,
  embedding USER-DEFINED,
  CONSTRAINT grievancecomments_pkey PRIMARY KEY (id),
  CONSTRAINT grievancecomments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT grievancecomments_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id)
);
CREATE TABLE public.grievancecosttracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL UNIQUE,
  allocation_id uuid,
  labor_cost numeric DEFAULT 0,
  material_cost numeric DEFAULT 0,
  equipment_cost numeric DEFAULT 0,
  transport_cost numeric DEFAULT 0,
  contractor_cost numeric DEFAULT 0,
  misc_cost numeric DEFAULT 0,
  total_cost numeric DEFAULT 0,
  budget_allocated numeric,
  budget_used numeric DEFAULT 0,
  budget_remaining numeric,
  cost_breakdown jsonb DEFAULT '{}'::jsonb,
  resource_usage jsonb DEFAULT '{"hours_worked": 0, "contractor_id": null, "equipment_used": [], "materials_used": [], "contractor_name": null, "workers_assigned": 0}'::jsonb,
  proof_documents jsonb DEFAULT '[]'::jsonb,
  approval_workflow jsonb DEFAULT '{"status": "Created", "created_by": null, "verified_by": null, "approved_by_head": null, "approved_by_finance": null}'::jsonb,
  status character varying DEFAULT 'within_budget'::character varying CHECK (status::text = ANY (ARRAY['within_budget'::character varying, 'near_limit'::character varying, 'exceeded'::character varying, 'approved'::character varying, 'pending_approval'::character varying]::text[])),
  work_location jsonb DEFAULT '{}'::jsonb,
  work_started_at timestamp with time zone,
  work_completed_at timestamp with time zone,
  CONSTRAINT grievancecosttracking_pkey PRIMARY KEY (id),
  CONSTRAINT grievancecosttracking_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT grievancecosttracking_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.budget_allocations(id)
);
CREATE TABLE public.grievanceescalations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL,
  escalation_level USER-DEFINED NOT NULL,
  escalated_to_officer_id uuid NOT NULL,
  escalated_by_officer_id uuid,
  reason text NOT NULL,
  action_taken text,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  overdue_hours integer,
  next_escalation_at timestamp with time zone,
  embedding USER-DEFINED,
  CONSTRAINT grievanceescalations_pkey PRIMARY KEY (id),
  CONSTRAINT grievanceescalations_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT grievanceescalations_escalated_to_officer_id_fkey FOREIGN KEY (escalated_to_officer_id) REFERENCES public.users(id),
  CONSTRAINT grievanceescalations_escalated_by_officer_id_fkey FOREIGN KEY (escalated_by_officer_id) REFERENCES public.users(id)
);
CREATE TABLE public.grievancefeedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL UNIQUE,
  citizen_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  additional_comments text,
  would_recommend boolean,
  satisfaction_level character varying,
  feedback_data jsonb,
  embedding USER-DEFINED,
  CONSTRAINT grievancefeedback_pkey PRIMARY KEY (id),
  CONSTRAINT grievancefeedback_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT grievancefeedback_citizen_id_fkey FOREIGN KEY (citizen_id) REFERENCES public.citizens(id)
);
CREATE TABLE public.grievanceworkflow (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL,
  step_number integer NOT NULL,
  status USER-DEFINED NOT NULL,
  officer_id uuid,
  officer_name character varying,
  action_taken text,
  notes text,
  gps_location jsonb,
  attachments jsonb,
  progress_percentage integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  embedding USER-DEFINED,
  CONSTRAINT grievanceworkflow_pkey PRIMARY KEY (id),
  CONSTRAINT grievanceworkflow_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT grievanceworkflow_officer_id_fkey FOREIGN KEY (officer_id) REFERENCES public.users(id)
);
CREATE TABLE public.materialinventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  material_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  department_id uuid NOT NULL,
  available_quantity numeric NOT NULL,
  unit character varying NOT NULL,
  min_threshold numeric NOT NULL,
  status USER-DEFINED DEFAULT 'adequate'::material_stock_status,
  location character varying,
  supplier character varying,
  unit_cost numeric,
  last_restocked timestamp with time zone,
  restock_history jsonb DEFAULT '[]'::jsonb,
  embedding USER-DEFINED,
  CONSTRAINT materialinventory_pkey PRIMARY KEY (id),
  CONSTRAINT materialinventory_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.migrations (
  id integer NOT NULL DEFAULT nextval('migrations_id_seq'::regclass),
  migration_name character varying NOT NULL UNIQUE,
  executed_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.official_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  official_id uuid NOT NULL,
  activity_type character varying NOT NULL,
  activity_description text,
  grievance_id uuid,
  department_id uuid,
  related_official_id uuid,
  activity_data jsonb DEFAULT '{}'::jsonb,
  performed_at_location character varying,
  ip_address character varying,
  user_agent text,
  CONSTRAINT official_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT official_activity_log_official_id_fkey FOREIGN KEY (official_id) REFERENCES public.government_officials(id),
  CONSTRAINT official_activity_log_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id),
  CONSTRAINT official_activity_log_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT official_activity_log_related_official_id_fkey FOREIGN KEY (related_official_id) REFERENCES public.government_officials(id)
);
CREATE TABLE public.official_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  official_id uuid NOT NULL,
  permission_type character varying NOT NULL CHECK (permission_type::text = ANY (ARRAY['View'::character varying, 'Create'::character varying, 'Update'::character varying, 'Delete'::character varying, 'Approve'::character varying, 'Reject'::character varying, 'Assign'::character varying, 'Transfer'::character varying, 'Escalate'::character varying, 'Close'::character varying, 'Reopen'::character varying]::text[])),
  resource_type character varying NOT NULL CHECK (resource_type::text = ANY (ARRAY['Grievance'::character varying, 'Budget'::character varying, 'Officer'::character varying, 'Department'::character varying, 'Report'::character varying, 'Task'::character varying, 'Announcement'::character varying, 'Document'::character varying]::text[])),
  scope_level character varying CHECK (scope_level::text = ANY (ARRAY['Own'::character varying, 'Ward'::character varying, 'City'::character varying, 'Taluka'::character varying, 'District'::character varying, 'State'::character varying, 'All'::character varying]::text[])),
  conditions jsonb DEFAULT '{}'::jsonb,
  granted_by uuid,
  granted_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  CONSTRAINT official_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT official_permissions_official_id_fkey FOREIGN KEY (official_id) REFERENCES public.government_officials(id),
  CONSTRAINT official_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.government_officials(id)
);
CREATE TABLE public.official_relationships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  official_id uuid NOT NULL,
  related_official_id uuid NOT NULL,
  relationship_type character varying NOT NULL CHECK (relationship_type::text = ANY (ARRAY['Reports To'::character varying, 'Supervises'::character varying, 'Collaborates With'::character varying, 'Coordinates With'::character varying, 'Escalates To'::character varying, 'Delegates To'::character varying]::text[])),
  can_view_data boolean DEFAULT false,
  can_assign_tasks boolean DEFAULT false,
  can_request_action boolean DEFAULT false,
  can_escalate boolean DEFAULT false,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT official_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT official_relationships_official_id_fkey FOREIGN KEY (official_id) REFERENCES public.government_officials(id),
  CONSTRAINT official_relationships_related_official_id_fkey FOREIGN KEY (related_official_id) REFERENCES public.government_officials(id)
);
CREATE TABLE public.policydocuments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title character varying NOT NULL,
  content text NOT NULL,
  department_id uuid,
  document_url text,
  embedding USER-DEFINED,
  metadata jsonb,
  is_active boolean DEFAULT true,
  CONSTRAINT policydocuments_pkey PRIMARY KEY (id),
  CONSTRAINT policydocuments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.predictivemaintenance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  equipment_id uuid NOT NULL,
  risk_level character varying DEFAULT 'low'::character varying,
  breakdown_probability numeric,
  predicted_failure_date timestamp with time zone,
  recommendation text,
  preventive_cost numeric,
  breakdown_cost numeric,
  utilization_rate numeric,
  last_maintenance timestamp with time zone,
  next_scheduled_maintenance timestamp with time zone,
  is_overdue boolean DEFAULT false,
  overdue_days integer,
  maintenance_scheduled boolean DEFAULT false,
  scheduled_date timestamp with time zone,
  embedding USER-DEFINED,
  CONSTRAINT predictivemaintenance_pkey PRIMARY KEY (id),
  CONSTRAINT predictivemaintenance_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id)
);
CREATE TABLE public.refreshtokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  revoked boolean DEFAULT false,
  user_type character varying DEFAULT 'user'::character varying,
  embedding USER-DEFINED,
  CONSTRAINT refreshtokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.repeatgrievancepatterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  zone character varying NOT NULL,
  area character varying,
  issue_type character varying NOT NULL,
  complaint_count integer NOT NULL,
  affected_citizens integer,
  time_period_days integer,
  priority character varying DEFAULT 'medium'::character varying,
  pattern_description text,
  ai_recommendation text,
  estimated_cost numeric,
  estimated_savings numeric,
  related_grievance_ids jsonb,
  is_addressed boolean DEFAULT false,
  addressed_at timestamp with time zone,
  embedding USER-DEFINED,
  CONSTRAINT repeatgrievancepatterns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.research_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  grievance_id uuid NOT NULL,
  research_query text NOT NULL,
  url text UNIQUE,
  content text,
  pinecone_id character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  source_type character varying DEFAULT 'web'::character varying,
  relevance_score numeric,
  CONSTRAINT research_documents_pkey PRIMARY KEY (id),
  CONSTRAINT research_documents_grievance_id_fkey FOREIGN KEY (grievance_id) REFERENCES public.usergrievance(id)
);
CREATE TABLE public.settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value jsonb NOT NULL,
  description text,
  category character varying DEFAULT 'general'::character varying,
  is_active boolean DEFAULT true,
  updated_by_user_id uuid,
  CONSTRAINT settings_pkey PRIMARY KEY (id),
  CONSTRAINT settings_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.state_central_officials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  level_type character varying NOT NULL,
  ministry_name character varying,
  jurisdiction text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT state_central_officials_pkey PRIMARY KEY (id),
  CONSTRAINT state_central_officials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.states (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  state_code character varying NOT NULL UNIQUE,
  state_name character varying NOT NULL,
  capital character varying,
  population bigint,
  area_sq_km numeric,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT states_pkey PRIMARY KEY (id)
);
CREATE TABLE public.taluka_officials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  district character varying NOT NULL,
  taluka character varying NOT NULL,
  designation character varying NOT NULL,
  block_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT taluka_officials_pkey PRIMARY KEY (id),
  CONSTRAINT taluka_officials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.talukas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  district_id uuid NOT NULL,
  taluka_code character varying NOT NULL UNIQUE,
  taluka_name character varying NOT NULL,
  headquarters character varying,
  population bigint,
  area_sq_km numeric,
  taluka_type character varying CHECK (taluka_type::text = ANY (ARRAY['Urban'::character varying, 'Rural'::character varying, 'Mixed'::character varying]::text[])),
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT talukas_pkey PRIMARY KEY (id),
  CONSTRAINT talukas_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.tenderapplications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tender_id uuid NOT NULL,
  contractor_id uuid NOT NULL,
  bid_amount numeric NOT NULL,
  proposal_document jsonb,
  technical_documents jsonb,
  financial_documents jsonb,
  status character varying DEFAULT 'submitted'::character varying,
  evaluation_score numeric,
  evaluation_notes text,
  is_shortlisted boolean DEFAULT false,
  embedding USER-DEFINED,
  CONSTRAINT tenderapplications_pkey PRIMARY KEY (id),
  CONSTRAINT tenderapplications_tender_id_fkey FOREIGN KEY (tender_id) REFERENCES public.tenders(id),
  CONSTRAINT tenderapplications_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES public.contractors(id)
);
CREATE TABLE public.tenders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tender_id character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  department_id uuid NOT NULL,
  created_by_officer_id uuid NOT NULL,
  estimated_value numeric,
  status USER-DEFINED DEFAULT 'draft'::tender_status,
  published_date timestamp with time zone,
  submission_deadline timestamp with time zone,
  opening_date timestamp with time zone,
  awarded_to_contractor_id uuid,
  awarded_date timestamp with time zone,
  requirements jsonb,
  documents jsonb,
  embedding USER-DEFINED,
  CONSTRAINT tenders_pkey PRIMARY KEY (id),
  CONSTRAINT tenders_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT tenders_created_by_officer_id_fkey FOREIGN KEY (created_by_officer_id) REFERENCES public.users(id),
  CONSTRAINT tenders_awarded_to_contractor_id_fkey FOREIGN KEY (awarded_to_contractor_id) REFERENCES public.contractors(id)
);
CREATE TABLE public.user_hierarchy (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  supervisor_id uuid,
  hierarchy_level character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT user_hierarchy_pkey PRIMARY KEY (id),
  CONSTRAINT user_hierarchy_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_hierarchy_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.users(id)
);
CREATE TABLE public.usergrievance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  grievance_id character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  grievance_text text,
  image_path text,
  image_description text,
  enhanced_query text,
  embedding USER-DEFINED,
  citizen_id uuid,
  department_id uuid,
  assigned_officer_id uuid,
  zone character varying,
  ward character varying,
  status USER-DEFINED DEFAULT 'submitted'::grievance_status,
  priority character varying DEFAULT 'medium'::character varying,
  validation_status character varying DEFAULT 'pending'::character varying,
  validation_score numeric,
  validation_reasoning text,
  extracted_location jsonb,
  extracted_address text,
  extracted_latitude numeric,
  extracted_longitude numeric,
  location_confidence character varying,
  validation_timestamp timestamp with time zone,
  processing_metadata jsonb,
  query_type jsonb,
  category jsonb,
  similar_cases_summary text,
  sentiment_priority jsonb,
  emotion jsonb,
  severity jsonb,
  patterns jsonb,
  fraud jsonb,
  department_info jsonb,
  policy_search jsonb,
  past_queries_summary text,
  full_result jsonb,
  sla_deadline timestamp with time zone,
  resolution_time numeric,
  is_escalated boolean DEFAULT false,
  escalation_level USER-DEFINED,
  comments jsonb DEFAULT '[]'::jsonb,
  workflow jsonb DEFAULT '{"status": "pending", "history": [], "started_at": null, "assigned_at": null, "resolved_at": null, "current_stage": "submitted"}'::jsonb,
  estimated_cost numeric,
  actual_cost numeric,
  escalated_at timestamp with time zone,
  citizen_feedback jsonb,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  embedding_status text DEFAULT 'pending'::text,
  CONSTRAINT usergrievance_pkey PRIMARY KEY (id),
  CONSTRAINT usergrievance_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id),
  CONSTRAINT usergrievance_citizen_id_fkey FOREIGN KEY (citizen_id) REFERENCES public.citizens(id),
  CONSTRAINT usergrievance_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT usergrievance_assigned_officer_id_fkey FOREIGN KEY (assigned_officer_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  full_name character varying NOT NULL,
  phone character varying,
  role USER-DEFINED NOT NULL DEFAULT 'citizen'::user_role,
  status USER-DEFINED NOT NULL DEFAULT 'active'::user_status,
  department_id uuid,
  profile_image text,
  address text,
  last_login timestamp with time zone,
  email_verified boolean DEFAULT false,
  verification_token text,
  reset_token text,
  reset_token_expiry timestamp with time zone,
  approval_status USER-DEFINED DEFAULT 'pending'::approval_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  department_name character varying,
  designation character varying,
  city character varying,
  embedding USER-DEFINED,
  verification_token_expiry timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT users_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.ward_officers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  ward_number character varying NOT NULL,
  city character varying NOT NULL,
  district character varying NOT NULL,
  zone character varying,
  reporting_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT ward_officers_pkey PRIMARY KEY (id),
  CONSTRAINT ward_officers_reporting_to_fkey FOREIGN KEY (reporting_to) REFERENCES public.users(id),
  CONSTRAINT ward_officers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.wards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  city_id uuid NOT NULL,
  ward_number character varying NOT NULL,
  ward_name character varying,
  population bigint,
  area_sq_km numeric,
  boundaries jsonb,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT wards_pkey PRIMARY KEY (id),
  CONSTRAINT wards_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);